language: node_js
node_js:
- '16.0'
script:
- npm install
- npm run build
- npm run coverage
- npm run report
after_success:
- curl -s https://codecov.io/bash > .codecov
- chmod +x .codecov
- ./.codecov -t c50d2b94-561a-4c13-beaf-6a96d3c4055e