language: node_js
node_js:
- '16.0'
script:
- npm install
- npm run build
- npm run coverage
- npm run report
after_success:
- curl -s https://codecov.io/bash > .codecov
- chmod +x .codecov
- ./.codecov -t 6e40abbf-4e64-4639-9fb3-447cdc7904c6